[package]
name = "marathon-client"
description = "Marathon CLI"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "marathon"
path = "src/main.rs"

[dependencies]
common.workspace = true
tracing.workspace = true

[lints]
workspace = true
