http:
  routers:
    marathon:
      rule: 'Host(`{{ env "MARATHON_DOMAIN" }}`)'
      service: marathon-svc
      tls:
        certResolver: letsencrypt
      entryPoints:
        - websecure
  services:
    marathon-svc:
      loadBalancer:
        servers:
          - url: h2c://orchestrator:8080
